barnehagefakta.get - WARNING - Change in response for id=1020871, archiving old result
barnehagefakta.get - WARNING - Change in response for id=2000612, archiving old result
barnehagefakta - ERROR - Un-handled exception for nbr_id = 1020871, skipping
Traceback (most recent call last):
  File "../barnehagefakta_osm.py", line 263, in main
    udir_tags = barnehagefakta_get(nbr_id, cache_dir=cache_dir)
  File "/Users/ob/Programming/Python/barnehagefakta_osm/barnehagefakta_get.py", line 107, in barnehagefakta_get
    j = barnehagefakta_get_json(nbr_id, *args, **kwargs)
  File "/Users/ob/Programming/Python/barnehagefakta_osm/barnehagefakta_get.py", line 94, in barnehagefakta_get_json
    file_util.rename_file(filename, d.strftime("-%Y-%m-%d-OUTDATED")) # move old one
  File "/Users/ob/Programming/Python/barnehagefakta_osm/utility_to_osm/file_util.py", line 20, in rename_file
    raise IOError('Filename "%s" already exists', filename)
IOError: [Errno Filename "%s" already exists] data/1804/barnehagefakta_no_nbrId1020871.json
